name: gloomhaven_decks
description: A companion app for the popular board game Gloomhaven.
#version: 1.1.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0
  path_provider: ^1.6.7
  wakelock: ^0.1.4+1
  shared_preferences: ^0.5.7
  recase: ^3.0.0
  sentry: ^3.0.1
  url_launcher: ^5.0.0


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: CharacterIcons
      fonts:
        - asset: fonts/CharacterIcons.ttf
    - family: InfusionIcons
      fonts:
        - asset: fonts/InfusionIcons.ttf
    - family: AttackEffectIcons
      fonts:
        - asset: fonts/AttackEffectIcons.ttf
    - family: ConditionIcons
      fonts:
        - asset: fonts/ConditionIcons.ttf
    - family: MiscIcons
      fonts:
        - asset: fonts/MiscIcons.ttf
    - family: PirataOne
      fonts:
        - asset: fonts/PirataOne-Gloomhaven.ttf
  assets:
    - images/cards/base/
    - images/cards/beasttyrant/
    - images/cards/berserker/
    - images/cards/brute/
    - images/cards/cragheart/
    - images/cards/doomstalker/
    - images/cards/mindthief/
    - images/cards/nightshroud/
    - images/cards/plagueherald/
    - images/cards/quartermaster/
    - images/cards/sawbones/
    - images/cards/scoundrel/
    - images/cards/soothsinger/
    - images/cards/spellweaver/
    - images/cards/summoner/
    - images/cards/sunkeeper/
    - images/cards/tinkerer/
    - images/cards/elementalist/
    - images/backgrounds/
    - images/attack_modifiers/
  uses-material-design: true
