name: gloomhaven_decks
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0
  path_provider: ^1.6.7
  wakelock: ^0.1.4+1
  shared_preferences: ^0.5.7


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: CharacterIcons
      fonts:
        - asset: fonts/CharacterIcons.ttf
    - family: PirataOne
      fonts:
        - asset: fonts/PirataOne-Gloomhaven.ttf
  assets:
    - images/cards/base/
    - images/cards/brute/
    - images/cards/cragheart/
    - images/cards/mindthief/
    - images/cards/nightshroud/
    - images/cards/scoundrel/
    - images/cards/spellweaver/
    - images/cards/sunkeeper/
    - images/cards/tinkerer/
    - images/backgrounds/
  uses-material-design: true
