/// Flutter icons AttackEffectIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AttackEffectIcons
///      fonts:
///       - asset: fonts/AttackEffectIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AttackEffectIcons {
  AttackEffectIcons._();

  static const _kFontFam = 'AttackEffectIcons';
  static const _kFontPkg = null;

  static const IconData push =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pierce =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_target =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heal =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pull =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
