/// Flutter icons InfusionIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InfusionIcons
///      fonts:
///       - asset: fonts/InfusionIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class InfusionIcons {
  InfusionIcons._();

  static const _kFontFam = 'InfusionIcons';
  static const _kFontPkg = null;

  static const IconData air =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earth =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dark =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
