/// Flutter icons ConditionIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ConditionIcons
///      fonts:
///       - asset: fonts/ConditionIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ConditionIcons {
  ConditionIcons._();

  static const _kFontFam = 'ConditionIcons';
  static const _kFontPkg = null;

  static const IconData bless = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData curse = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disarm = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData immobilize = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wound = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muddle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stun = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poison = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invisible = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strengthen = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData regenerate = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
