/// Flutter icons ItemType
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ItemType
///      fonts:
///       - asset: fonts/ItemTypeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ItemTypeIcons {
  ItemTypeIcons._();

  static const _kFontFam = 'ItemTypeIcons';
  static const _kFontPkg = null;

  static const IconData body = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feet = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData head = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData one_handed = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_item = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two_handed = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
