/// Flutter icons MiscIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MiscIcons
///      fonts:
///       - asset: fonts/MiscIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MiscIcons {
  MiscIcons._();

  static const _kFontFam = 'MiscIcons';
  static const _kFontPkg = null;

  static const IconData rolling =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_one =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
